name: Go API Deploy to AWS ECS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24.1"

      - name: Run tests (optional but recommended)
        run: go test ./...

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/open-typing-api:latest .

      - name: Log in to AWS using GitHub Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/open-typing-api:latest

      - name: Register new task definition revision
        run: |
          task_definition=$(aws ecs describe-task-definition --task-definition open-typing-api-task-definition)
          new_task_definition=$(echo "$task_definition" | jq '.taskDefinition | {family, containerDefinitions, executionRoleArn, taskRoleArn, requiresCompatibilities, networkMode, cpu, memory}')
          aws ecs register-task-definition --cli-input-json "$new_task_definition"

      - name: Update ECS Service to Use New Task Definition
        run: |
          latest_revision=$(aws ecs describe-task-definition --task-definition open-typing-api-task-definition --query "taskDefinition.revision" --output text)
          aws ecs update-service \
            --cluster my-cluster \
            --load-balancers targetGroupArn="${{ secrets.LOAD_BALANCER_ARN }}",containerName=open-typing-api,containerPort=8080 \
            --service open-typing-api-service \
            --task-definition open-typing-api-task-definition:$latest_revision \
            --force-new-deployment
